package com.leodev.hybrid_banking_system.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * Represents a bank account in the Hybrid Banking System.
 * This entity is persisted in the database and stores
 * the core financial data of a bank account.
 *
 * Each account has:
 * - A unique account number
 * - A monetary balance stored with financial precision
 *
 * This class contains no business logic.
 * It is a pure domain entity.
 */

@Getter @Setter
@NoArgsConstructor @AllArgsConstructor
@Builder
@Entity
@Table(name = "accounts")
public class Account {

    /**
     * Unique identifier of the account.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique account number (e.g., ACC001).
     * Must not be null and must be unique.
     */
    @Column(nullable = false, unique = true, length = 30)
    private String number;

    /**
     * Current account balance.
     */
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal balance;
}
